language: node_js
node_js:
  - "5.0"
  - "6"
  - "iojs"
script:
  - npm install
  - npm run test
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install
