sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "5"
  - "latest"
before_install:
  - npm i -g npm@^5.0.0
before_script:
  - npm prune
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - export $(cat .to_export_back) &> /dev/null
branches:
  only:
    - master
